import type { ReactNode } from 'react';

/*
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
*/
export { metadata, viewport } from 'next-sanity/studio'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
